eureka:
    client:
        fetch-registry: false
        register-with-eureka: false
        healthcheck:
            enabled: true
    server:
        renewal-percent-threshold: 0.85
        batch-replication: true
    instance:
        appname: discovery-server
        prefer-ip-address: false
        secure-port-enabled: true
        

management:
  endpoint:
    health:
      enabled: true
      show-details: always
    shutdown:
      enabled: true
    
server:
    port: 8761
    
spring:
    application:
        name: eureka
    #security:
     #   user:
      #     name: srv-app-discovery
       #    password: generat3aRand0mStrin5

